#!/usr/bin/env bash
set -euo pipefail

VERSION='1.0.0'
HOURS=1
ALL_EVENTS="ALL_EVENTS"
TOMORROW_EVENTS="TOMORROW_EVENTS"
DAILY_EVENTS="DAILY_EVENTS"

usage() { cat << _EOF_
Usage: events [OPTION]
Show the events.
     -a,    print all the events (weekly)
     -d,    print events of the specified day (default current day)
     -h,    display this help and exit
     -v,    output version information and exit

Exit status:
     0      if OK,
     1      if minor problems (e.g., wrong specified day)

License:
    License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

_EOF_
1>&2; exit 1; }

show_daily_events(){
    local day

    case "${1}" in
        Mon)
            day=1
            ;;
        Tue)
            day=2
            ;;
        Wed)
            day=3
            ;;
        Thu)
            day=4
            ;;
        Fri)
            day=5
            ;;
        *)
            echo "Wrong specified day"
            exit 1
            ;;
    esac

    day=$((day + 1))
    DAILY_EVENTS=$(echo "${TIMETABLE}" | awk  -F '|' "{print \$${HOURS} \"\t\" \$${day}}")
    echo "${DAILY_EVENTS}"
}

show-tomorrow-events(){
    show_daily_events "$(date --date 'next day' +%a)"
}

show_all_events(){
    ALL_EVENTS=$(echo "${TIMETABLE}" | column -s "|" -L -t)
    echo "${ALL_EVENTS}"
}

MODE="NO_MODE"
day=""

while getopts "atd:c:hv" o; do
    case "${o}" in
        a)
            echo "Show all events"
            MODE=$ALL_EVENTS
            ;;
        t)
            echo "Show tomorrow events"
            MODE=$TOMORROW_EVENTS #tomorrow_events="true"
            ;;
        d)
            [[ -v $OPTARG ]] && day=${OPTARG:0:3}
            MODE=$DAILY_EVENTS #daily_events="true"
            ;;
        c)
            CALENDAR=${OPTARG}
            echo "Show events of ${CALENDAR}"
            ;;
        v)
            echo "Version: ${VERSION}"
            ;;
        h | *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $day == "" ]]; then
    day="$(date +%a)"
fi

 case "${MODE}" in
        "$ALL_EVENTS")
            echo "Show all events"
            ;;
        "$TOMORROW_EVENTS")
            echo "Show tomorrow events"
            ;;
        "$DAILY_EVENTS")
            echo "Show events of day"
            ;;
        *)
            usage
            ;;
    esac

exit 0
